export const FETCH_BLOGS = 'FETCH_BLOGS';
export const FETCH_BLOG = 'FETCH_BLOG';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_FEATURES = 'FETCH_FEATURES';
export const FETCH_RECENT_BLOGS = 'FETCH_RECENT_BLOGS';
export const FETCH_AUTHOR = 'FETCH_AUTHOR';
export const FETCH_CATEGORY_BLOGS = 'FETCH_CATEGORY_BLOGS';
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const GET_PAGINATION  = 'GET_PAGINATION';



